defaults:
    - agent: sac

env: cheetah_run

# this needs to be specified manually
experiment: test_exp

num_train_steps: 1e6
replay_buffer_capacity: ${num_train_steps}

renormalize: True
renormalize_freq: 1000

num_seed_steps: 5000

eval_frequency: 10000
num_eval_episodes: 10
fixed_eval: True

device: cuda

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
save_video: true
save_frequency: 10000
save_latest: true


seed: 1

# For debugging:
num_initial_states: null # Use a subset of initial states
max_episode_steps: null # If set, use shorter episodes

# hydra configuration
hydra:
    name: ${envs}
    run:
        dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}
