defaults:
    - agent: sac
    - fwd_model: fc_ensemble
    - fwd_dataset: bootstrap_dataset

env: hopper_hop

# this needs to be specified manually
experiment: test_exp

num_train_steps: 125000
env_buffer_capacity: ${num_train_steps}
agent_update_freq: 20  # number of agent updates per envs step
fit_fwd_freq: 250 # number of envs steps per forward model update

rollout_batch_size: 10000
num_rollouts: 10
rollouts_retained: 40
h_sched: 20,100,1,1  # optional - string start_epoch,end_epoch,start_length,end_length
model_buffer_capacity: 400000  # rollout_batch_size * rollouts_retained * rollout_length

num_seed_steps: 5000

eval_frequency: 10000
num_eval_episodes: 10

device: cuda

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
save_video: true


seed: 1


# hydra configuration
hydra:
    name: ${envs}
    run:
        dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}